### PR TITLE
feat: Install NLO dependencies through `mg5_aMC install`

### LINKED ISSUE #48: Investigate additional requirements for NLO processes
Hm, seems that for NLO there are additional missing dependencies that I'm missing as well

```
MG5_aMC>output test_nlo
First output using loop matrix-elements has been detected. Now asking for loop reduction:
For loop computations, MadLoop requires dedicated tools to perform the reduction of loop Feynman diagrams using OPP-based and/or TIR approaches.

Which one do you want to install? (this needs to be done only once)
1. cuttools  (OPP) [0711.3596]   : will be installed (required)
2. iregi     (TIR) [1405.0301]   : will be installed (required)
3. ninja     (OPP) [1403.1229]   : will be installed (recommended)
4. collier   (TIR) [1604.06792]  : will be installed (recommended)
5. golem     (TIR) [0807.0605]   : do not install
You can:
 -> hit 'enter' to proceed
 -> type a number to cycle its options
 -> enter the following command:
    {tool_name} [install|noinstall|{prefixed_installation_path}]

If you are unsure about what this question means, just type enter to proceed.
```

This is something that I can follow up with more with @suchitakulkarni &mdash; thank you though, Suchita, this is _very_ important to know about!

_Originally posted by @matthewfeickert in https://github.com/scailfin/MadGraph5_aMC-NLO/issues/46#issuecomment-925809730_

### PR DESCRIPTION
**Pull request by matthewfeickert**
Resolves #48

Given how frustratingly difficult it is to find and install `cuttools` and `iregi` like normal well behaved software, temporarily cave and use the `mg5_aMC install` command to install NLO recommended dependencies `ninja` and `collier`. Then run a NLO process to automatically pick up the NLO dependencies `cuttools` and `iregi`.

Run the same process in CI as a test to ensure that things were installed as expected.

```
* Install NLO recommended dependencies ninja and collier with `mg5_aMC install`
* Install NLO dependencies cuttools and iregi automatically by running an NLO process
* Add TODO to find a way to install globally with better control
* Add test in CI to ensure all dependencies are installed
* Add list of installed NLO dependencies to README
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
I'm giving up and installing the NLO dependencies with `mg5_aMC install` for now, but in the future there should be some more sustainable and transparent way to approach this.

**Comment by matthewfeickert** [comment]
@suchitakulkarni can you try this https://github.com/scailfin/MadGraph5_aMC-NLO/issues/46#issuecomment-925799035 again with

```
docker pull scailfin/madgraph5-amc-nlo:mg5_amc3.2.0
```

? I believe that the dependencies should be there now such that

```console
$ printf "generate p p > e+ e- aEW=2 aS=0 [QCD]\noutput test_nlo\nlaunch test_nlo\n" > test_NLO.mg5
$ cat test_NLO.mg5 
generate p p > e+ e- aEW=2 aS=0 [QCD]
output test_nlo
launch test_nlo
$ docker run --rm -v $PWD:$PWD -w $PWD scailfin/madgraph5-amc-nlo:mg5_amc3.2.0 'mg5_aMC test_NLO.mg5'
```

should run as expected.

**Comment by suchitakulkarni** [comment]
I confirm that this works on mu machine. I pulled the image and tried 

```docker run --rm -v $PWD:$PWD -w $PWD scailfin/madgraph5-amc-nlo:mg5_amc3.2.0 'mg5_aMC test_NLO.mg5'```

**Comment by matthewfeickert** [comment]
> I confirm that this works on my machine

Yay! Thanks for confirming. :)

I assume that there will be some other pain points and papercuts for expert users like you, but thank you for bringing this to my attention in the first place! If I can ask you to continue to report back problems that would be great. :slightly_smiling_face:

**Pull request merged**
